function PSshowCLIDialog(cliText)
%% PSshowCLIDialog - show CLI text for hand copying when the clipboard is not reachable

screensz = get(0, 'ScreenSize');
dlg = figure('Name', 'BF CLI Commands', 'NumberTitle', 'off', ...
    'Color', [.15 .15 .15], ...
    'Position', round([screensz(3)*.3 screensz(4)*.25 460 380]));
uicontrol(dlg, 'Style', 'text', 'String', 'Select All + Copy:', ...
    'Units', 'normalized', 'Position', [.05 .90 .9 .07], ...
    'FontSize', 11, 'BackgroundColor', [.15 .15 .15], 'ForegroundColor', [.9 .9 .9]);
uicontrol(dlg, 'Style', 'edit', 'Max', 100, 'String', cliText, ...
    'Units', 'normalized', 'Position', [.05 .12 .9 .76], ...
    'HorizontalAlignment', 'left', 'FontName', 'Monospace', 'FontSize', 10, ...
    'BackgroundColor', [.1 .1 .1], 'ForegroundColor', [.9 .9 .9]);
uicontrol(dlg, 'Style', 'pushbutton', 'String', 'Close', ...
    'Units', 'normalized', 'Position', [.35 .02 .3 .08], ...
    'FontSize', 11, 'BackgroundColor', [.3 .3 .3], 'ForegroundColor', [.9 .9 .9], ...
    'Callback', @(~,~) close(dlg));

end
